<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Atlas_Domain\Atlas_Domain.csproj" />
    <ProjectReference Include="..\Atlas_Shared\Atlas_Shared.csproj" />
    <ProjectReference Include="..\Atlas_Market_Data\Atlas_Market_Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
